const skillCategories: { title: string; tags: string[] }[] = [
  {
    title: "Frontend",
    tags: [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "HTML5",
      "CSS3",
      "Styled Components",
      "Shadcn UI",
      "Radix",
      "Zod",
      "React Hook Form",
      "Framer Motion",
      "Zustand",
      "Tanstack Query",
      "Design Systems",
    ],
  },
  {
    title: "Mobile",
    tags: [
      "React Native",
      "Expo",
      "Android Studio",
      "Async Storage",
      "Push Notifications",
      "React Navigation",
      "Play Store",
      "App Store",
    ],
  },
  {
    title: "Backend",
    tags: [
      "Node.js",
      "Express",
      "Fastify",
      "Java",
      "Spring Boot",
      "Jest",
      "JPA",
      "Hibernate",
      "Scalar",
      "Swagger",
      "JWT",
      "Prisma",
      "SOLID",
      "TDD",
    ],
  },
  {
    title: "Banco de Dados",
    tags: ["PostgreSQL", "MongoDB", "MySQL", "Firebase", "Supabase"],
  },
  {
    title: "DevOps & Ferramentas",
    tags: [
      "Git",
      "Docker",
      "Figma",
      "Vercel",
      "Cloudflare",
      "Render",
      "CI/CD",
      "AWS",
    ],
  },
];
